/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_hugegraph_util_collection_JniBytesSetIterator */

#ifndef _Included_com_baidu_hugegraph_util_collection_JniBytesSetIterator
#define _Included_com_baidu_hugegraph_util_collection_JniBytesSetIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSetIterator
 * Method:    next
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSetIterator_next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSetIterator
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSetIterator_hasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSetIterator
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSetIterator_deleteNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
