/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_hugegraph_util_collection_JniLongSet */

#ifndef _Included_com_baidu_hugegraph_util_collection_JniLongSet
#define _Included_com_baidu_hugegraph_util_collection_JniLongSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    init
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_init
  (JNIEnv *, jobject, jboolean, jint, jint);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    add
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_add
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    addExclusive
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_addExclusive
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    addAll
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_addAll
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    contains
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_contains
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    remove
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_remove
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    erase
 * Signature: (JJ)Z
 */
JNIEXPORT jint JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_erase
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_deleteNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSet
 * Method:    iterator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSet_iterator
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
