/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_hugegraph_util_collection_JniLongSetIterator */

#ifndef _Included_com_baidu_hugegraph_util_collection_JniLongSetIterator
#define _Included_com_baidu_hugegraph_util_collection_JniLongSetIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSetIterator
 * Method:    next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSetIterator_next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSetIterator
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSetIterator_hasNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniLongSetIterator
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_hugegraph_util_collection_JniLongSetIterator_deleteNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
