/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_hugegraph_util_collection_JniBytesSet */

#ifndef _Included_com_baidu_hugegraph_util_collection_JniBytesSet
#define _Included_com_baidu_hugegraph_util_collection_JniBytesSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    init
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_init
  (JNIEnv *, jobject, jboolean, jint, jint);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    add
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_add
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    addExclusive
 * Signature: (J[BJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_addExclusive
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    addAll
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_addAll
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    contains
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_contains
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    remove
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_remove
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    erase
 * Signature: (JJ)Z
 */
JNIEXPORT jint JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_erase
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_deleteNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_baidu_hugegraph_util_collection_JniBytesSet
 * Method:    iterator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_hugegraph_util_collection_JniBytesSet_iterator
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
